create extension if not exists pgcrypto;

create table if not exists public.krisenfest_documents (
  scope_kind text not null,
  scope_id text not null,
  namespace text not null,
  payload_json jsonb not null,
  version integer not null default 1,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (scope_kind, scope_id, namespace)
);

create table if not exists public.krisenfest_audit_events (
  sequence bigint generated by default as identity primary key,
  tenant_id text not null,
  event_id text not null,
  created_at timestamptz not null default timezone('utc', now()),
  payload_json jsonb not null
);

create index if not exists idx_krisenfest_audit_events_tenant_sequence
  on public.krisenfest_audit_events (tenant_id, sequence desc);

create or replace function public.krisenfest_upsert_document(
  p_scope_kind text,
  p_scope_id text,
  p_namespace text,
  p_payload_json jsonb,
  p_expected_version integer default null,
  p_updated_at timestamptz default timezone('utc', now())
)
returns table (
  payload_json jsonb,
  version integer,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.krisenfest_documents%rowtype;
  v_now timestamptz := coalesce(p_updated_at, timezone('utc', now()));
begin
  select *
    into v_row
    from public.krisenfest_documents
   where scope_kind = p_scope_kind
     and scope_id = p_scope_id
     and namespace = p_namespace
   for update;

  if not found then
    if p_expected_version is not null and p_expected_version <> 0 then
      raise exception using
        errcode = 'P0001',
        message = format('VERSION_CONFLICT|0|');
    end if;

    insert into public.krisenfest_documents (
      scope_kind,
      scope_id,
      namespace,
      payload_json,
      version,
      updated_at
    ) values (
      p_scope_kind,
      p_scope_id,
      p_namespace,
      p_payload_json,
      1,
      v_now
    )
    returning public.krisenfest_documents.payload_json,
              public.krisenfest_documents.version,
              public.krisenfest_documents.updated_at
         into payload_json, version, updated_at;

    return next;
    return;
  end if;

  if p_expected_version is not null and v_row.version <> p_expected_version then
    raise exception using
      errcode = 'P0001',
      message = format('VERSION_CONFLICT|%s|%s', v_row.version, coalesce(v_row.updated_at::text, ''));
  end if;

  update public.krisenfest_documents
     set payload_json = p_payload_json,
         version = v_row.version + 1,
         updated_at = v_now
   where scope_kind = p_scope_kind
     and scope_id = p_scope_id
     and namespace = p_namespace
  returning public.krisenfest_documents.payload_json,
            public.krisenfest_documents.version,
            public.krisenfest_documents.updated_at
       into payload_json, version, updated_at;

  return next;
end;
$$;

create or replace function public.krisenfest_append_audit_event(
  p_tenant_id text,
  p_event jsonb,
  p_limit integer default 300
)
returns table (
  payload_json jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 300), 1000));
  v_created_at timestamptz := coalesce((p_event ->> 'at')::timestamptz, timezone('utc', now()));
  v_event_id text := coalesce(nullif(p_event ->> 'id', ''), gen_random_uuid()::text);
begin
  insert into public.krisenfest_audit_events (
    tenant_id,
    event_id,
    created_at,
    payload_json
  ) values (
    p_tenant_id,
    v_event_id,
    v_created_at,
    coalesce(p_event, '{}'::jsonb)
  );

  delete from public.krisenfest_audit_events
   where sequence in (
     select sequence
       from (
         select sequence,
                row_number() over (partition by tenant_id order by sequence desc) as rn
           from public.krisenfest_audit_events
          where tenant_id = p_tenant_id
       ) q
      where q.rn > v_limit
   );

  return query
    select e.payload_json
      from public.krisenfest_audit_events e
     where e.tenant_id = p_tenant_id
     order by e.sequence desc
     limit v_limit;
end;
$$;

create or replace function public.krisenfest_replace_audit_events(
  p_tenant_id text,
  p_entries jsonb,
  p_limit integer default 300
)
returns table (
  payload_json jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 300), 1000));
  v_entries jsonb := case
    when jsonb_typeof(p_entries) = 'array' then p_entries
    else '[]'::jsonb
  end;
begin
  delete from public.krisenfest_audit_events
   where tenant_id = p_tenant_id;

  insert into public.krisenfest_audit_events (
    tenant_id,
    event_id,
    created_at,
    payload_json
  )
  select
    p_tenant_id,
    coalesce(nullif(value ->> 'id', ''), gen_random_uuid()::text),
    coalesce((value ->> 'at')::timestamptz, timezone('utc', now())),
    value
  from jsonb_array_elements(v_entries) with ordinality as x(value, ord)
  order by ord desc
  limit v_limit;

  return query
    select e.payload_json
      from public.krisenfest_audit_events e
     where e.tenant_id = p_tenant_id
     order by e.sequence desc
     limit v_limit;
end;
$$;

revoke all on public.krisenfest_documents from anon, authenticated;
revoke all on public.krisenfest_audit_events from anon, authenticated;
revoke execute on function public.krisenfest_upsert_document(text, text, text, jsonb, integer, timestamptz) from anon, authenticated;
revoke execute on function public.krisenfest_append_audit_event(text, jsonb, integer) from anon, authenticated;
revoke execute on function public.krisenfest_replace_audit_events(text, jsonb, integer) from anon, authenticated;

grant select, insert, update, delete on public.krisenfest_documents to service_role;
grant select, insert, update, delete on public.krisenfest_audit_events to service_role;
grant execute on function public.krisenfest_upsert_document(text, text, text, jsonb, integer, timestamptz) to service_role;
grant execute on function public.krisenfest_append_audit_event(text, jsonb, integer) to service_role;
grant execute on function public.krisenfest_replace_audit_events(text, jsonb, integer) to service_role;
